model: unet_edge_v2
loss:
  weights:
    bce: 1
    dice: 1
    mse: 0.5

save_every: 5
lr: 0.0001
batch_size: 10
epochs: 100
weight_decay: 0.00001
log_every: 1

data_root: /content/data

pattern_types:
  - mental_layer
  - mental_line
  - mental_corner
  - mental_curve
  - mental_head
  - mental_circle

output_root: /content/drive/MyDrive/Colab Notebooks/experiments
output_dir: exp_unet_edge_v2_bce_dice_0.5mse_15bias
device: auto
num_workers: 0
seed: 42

tip_weight: 15
tip_roi_height: 80
tip_pad_x: 25
